apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: script-  
spec:
  entrypoint: gen-random-int       
  templates:
  - name: gen-random-int
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(1, 100)
        print(i)
