apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: tempaltes-workflow-  
spec:
  entrypoint: hello-steps        
  templates:
  - name: hello-steps
    steps:
    - - name: step1
        template: container
    - - name: step2a
        template: gen-random-int
      - name: step2b
        template: gen-random-int
      - name: step2c
        template: gen-random-int
    - - name: step3
        template: container

  - name: container            
    container:
      image: busybox
      command: [echo]
      args: ["hello world"]
  - name: gen-random-int
    script:
      image: python:alpine3.6
      command: [python]
      source: |
        import random
        i = random.randint(1, 100)
        print(i)             
