apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  generateName: hello-world-global-parameters-
spec:
  entrypoint: whalesay
  arguments:
    parameters:
    - name: log-level
      value: WARN

  templates:
  - name: whalesay
    container:
      # run cowsay with that message input parameter as args
      image: busybox
      env:
      - name: LOG_LEVEL
        value: "{{workflow.parameters.log-level}}"
      command: [printenv]
